---
# ***1. SELECT + WHERE — filter rows***
---

In [29]:
import sqlite3
import pandas as pd
df = pd.read_csv('imdb_top_1000_cleaned.csv')
conn = sqlite3.connect('imdb.db')
df.to_sql('movies', conn, if_exists='replace', index=False)
result = pd.read_sql_query("SELECT * FROM movies LIMIT 5", conn)
result

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Decade
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994.0,A,142,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0,1990.0
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972.0,A,175,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0,1970.0
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008.0,UA,152,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0,2000.0
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974.0,A,202,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0,1970.0
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957.0,U,96,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000.0,1950.0

In [8]:
query = """
SELECT Series_Title, IMDB_Rating, Released_Year	
FROM movies
WHERE IMDB_Rating >= 8.5
ORDER BY IMDB_Rating DESC
"""
pd.read_sql_query(query, conn)

,Series_Title,IMDB_Rating,Released_Year
0,The Shawshank Redemption,9.3,1994.0
1,The Godfather,9.2,1972.0
2,The Dark Knight,9.0,2008.0
3,The Godfather: Part II,9.0,1974.0
4,12 Angry Men,9.0,1957.0
5,The Lord of the Rings: The Return of the King,8.9,2003.0
6,Pulp Fiction,8.9,1994.0
7,Schindler's List,8.9,1993.0
8,Inception,8.8,2010.0
9,Fight Club,8.8,1999.0
10,The Lord of the Rings: The Fellowship of the Ring,8.8,2001.0
11,Forrest Gump,8.8,1994.0
12,"Il buono, il brutto, il cattivo",8.8,1966.0
13,The Lord of the Rings: The Two Towers,8.7,2002.0
14,The Matrix,8.7,1999.0
15,Goodfellas,8.7,1990.0
16,Star Wars: Episode V - The Empire Strikes Back,8.7,1980.0
17,One Flew Over the Cuckoo's Nest,8.7,1975.0
18,Hamilton,8.6,2020.0
19,Gisaengchung,8.6,2019.0
20,Soorarai Pottru,8.6,2020.0
21,Interstellar,8.6,2014.0
22,Cidade de Deus,8.6,2002.0
23,Sen to Chihiro no kamikakushi,8.6,2001.0
24,Saving Private Ryan,8.6,1998.0
25,The Green Mile,8.6,1999.0
26,La vita è bella,8.6,1997.0
27,Se7en,8.6,1995.0
28,The Silence of the Lambs,8.6,1991.0
29,Star Wars,8.6,1977.0
30,Seppuku,8.6,1962.0
31,Shichinin no samurai,8.6,1954.0
32,It's a Wonderful Life,8.6,1946.0
33,Joker,8.5,2019.0
34,Whiplash,8.5,2014.0
35,The Intouchables,8.5,2011.0
36,The Prestige,8.5,2006.0
37,The Departed,8.5,2006.0
38,The Pianist,8.5,2002.0
39,Gladiator,8.5,2000.0
40,American History X,8.5,1998.0
41,The Usual Suspects,8.5,1995.0
42,Léon,8.5,1994.0
43,The Lion King,8.5,1994.0
44,Terminator 2: Judgment Day,8.5,1991.0
45,Nuovo Cinema Paradiso,8.5,1988.0
46,Hotaru no haka,8.5,1988.0
47,Back to the Future,8.5,1985.0
48,Once Upon a Time in the West,8.5,1968.0
49,Psycho,8.5,1960.0
50,Casablanca,8.5,1942.0
51,Modern Times,8.5,1936.0
52,City Lights,8.5,1931.0

---
# ***2. GROUP BY + Aggregates — summarize by category***
---

In [10]:
query = """
SELECT Genre, COUNT(*) as movie_count, ROUND(AVG(IMDB_Rating), 2) as avg_rating
FROM movies
GROUP BY Genre
ORDER BY IMDB_Rating DESC
LIMIT 10
"""
pd.read_sql_query(query, conn)

                       Genre  movie_count  avg_rating
0                      Drama           85        7.98
1               Crime, Drama           26        8.16
2       Action, Crime, Drama           30        7.88
3  Biography, Drama, History           28        8.02
4   Action, Adventure, Drama           14        8.15
5                    Western            4        8.35
6             Drama, Romance           37        7.94
7  Action, Adventure, Sci-Fi           21        7.93
8    Biography, Crime, Drama           16        7.92
9             Action, Sci-Fi            3        8.40

---
# ***3. LIKE — pattern matching on strings***
---

In [14]:
query = """
SELECT Series_Title, Genre, IMDB_Rating
FROM movies
WHERE Genre LIKE '%DRAMA%'
ORDER BY IMDB_Rating DESC
LIMIT 10
"""
pd.read_sql_query(query, conn)

,Series_Title,Genre,IMDB_Rating
0,The Shawshank Redemption,Drama,9.3
1,The Godfather,"Crime, Drama",9.2
2,The Dark Knight,"Action, Crime, Drama",9.0
3,The Godfather: Part II,"Crime, Drama",9.0
4,12 Angry Men,"Crime, Drama",9.0
5,The Lord of the Rings: The Return of the King,"Action, Adventure, Drama",8.9
6,Pulp Fiction,"Crime, Drama",8.9
7,Schindler's List,"Biography, Drama, History",8.9
8,Fight Club,Drama,8.8
9,The Lord of the Rings: The Fellowship of the Ring,"Action, Adventure, Drama",8.8

---
# ***4. INNER JOIN — combine two tables***
---

In [34]:
directors_df = pd.DataFrame({
    'Director' : ['Christopher Nolan', 'Frank Darabont', 'Francis Ford Coppola', 'David Fincher'],
    'Nationality' : ['British', 'American', 'American', 'American']
})
directors_df.to_sql('directors', conn, if_exists='replace', index=False)
result = pd.read_sql_query("SELECT * FROM directors LIMIT 5", conn)
result

               Director Nationality
0     Christopher Nolan     British
1        Frank Darabont    American
2  Francis Ford Coppola    American
3         David Fincher    American

In [35]:
query = """
SELECT m.Series_Title, m.IMDB_Rating, d.Nationality
FROM movies m
INNER JOIN directors d ON m.Director = d.Director
ORDER BY m.IMDB_Rating DESC
"""
pd.read_sql_query(query, conn)

                           Series_Title  IMDB_Rating Nationality
0              The Shawshank Redemption          9.3    American
1                         The Godfather          9.2    American
2                       The Dark Knight          9.0     British
3                The Godfather: Part II          9.0    American
4                             Inception          8.8     British
5                            Fight Club          8.8    American
6                          Interstellar          8.6     British
7                        The Green Mile          8.6    American
8                                 Se7en          8.6    American
9                          The Prestige          8.5     British
10                The Dark Knight Rises          8.4     British
11                              Memento          8.4     British
12                       Apocalypse Now          8.4    American
13                        Batman Begins          8.2     British
14                            Gone Girl          8.1    American
15                              Dunkirk          7.8     British
16      The Girl with the Dragon Tattoo          7.8    American
17  The Curious Case of Benjamin Button          7.8    American
18                             The Game          7.8    American
19                     The Conversation          7.8    American
20                   The Social Network          7.7    American
21                               Zodiac          7.7    American
22              The Godfather: Part III          7.6    American

---
# ***5. Subquery — query inside a query***
---

In [43]:
query = """
SELECT Series_Title, IMDB_Rating, Director
FROM movies
WHERE IMDB_Rating > (SELECT AVG(IMDB_Rating) FROM movies)
ORDER BY IMDB_Rating DESC
LIMIT 10
"""
pd.read_sql_query(query, conn)

,Series_Title,IMDB_Rating,Director
0,The Shawshank Redemption,9.3,Frank Darabont
1,The Godfather,9.2,Francis Ford Coppola
2,The Dark Knight,9.0,Christopher Nolan
3,The Godfather: Part II,9.0,Francis Ford Coppola
4,12 Angry Men,9.0,Sidney Lumet
5,The Lord of the Rings: The Return of the King,8.9,Peter Jackson
6,Pulp Fiction,8.9,Quentin Tarantino
7,Schindler's List,8.9,Steven Spielberg
8,Inception,8.8,Christopher Nolan
9,Fight Club,8.8,David Fincher

---
# ***6. Window Functions — rank without collapsing rows***
---

In [45]:
query = """
SELECT Series_Title, IMDB_Rating, Director,
       RANK() OVER (ORDER BY IMDB_Rating DESC) as rank
FROM movies
LIMIT 20
"""
pd.read_sql_query(query, conn)

,Series_Title,IMDB_Rating,Director,rank
0,The Shawshank Redemption,9.3,Frank Darabont,1
1,The Godfather,9.2,Francis Ford Coppola,2
2,The Dark Knight,9.0,Christopher Nolan,3
3,The Godfather: Part II,9.0,Francis Ford Coppola,3
4,12 Angry Men,9.0,Sidney Lumet,3
5,The Lord of the Rings: The Return of the King,8.9,Peter Jackson,6
6,Pulp Fiction,8.9,Quentin Tarantino,6
7,Schindler's List,8.9,Steven Spielberg,6
8,Inception,8.8,Christopher Nolan,9
9,Fight Club,8.8,David Fincher,9
10,The Lord of the Rings: The Fellowship of the Ring,8.8,Peter Jackson,9
11,Forrest Gump,8.8,Robert Zemeckis,9
12,"Il buono, il brutto, il cattivo",8.8,Sergio Leone,9
13,The Lord of the Rings: The Two Towers,8.7,Peter Jackson,14
14,The Matrix,8.7,Lana Wachowski,14
15,Goodfellas,8.7,Martin Scorsese,14
16,Star Wars: Episode V - The Empire Strikes Back,8.7,Irvin Kershner,14
17,One Flew Over the Cuckoo's Nest,8.7,Milos Forman,14
18,Hamilton,8.6,Thomas Kail,19
19,Gisaengchung,8.6,Bong Joon Ho,19

In [47]:
query = """
SELECT Series_Title, Genre, IMDB_Rating, Director,
       RANK() OVER (PARTITION BY Genre ORDER BY IMDB_Rating DESC) as genre_rank
FROM movies
LIMIT 30
"""
pd.read_sql_query(query, conn)

,Series_Title,Genre,IMDB_Rating,Director,genre_rank
0,The Dark Knight Rises,"Action, Adventure",8.4,Christopher Nolan,1
1,Raiders of the Lost Ark,"Action, Adventure",8.4,Steven Spielberg,1
2,Batman Begins,"Action, Adventure",8.2,Christopher Nolan,3
3,Indiana Jones and the Last Crusade,"Action, Adventure",8.2,Steven Spielberg,3
4,First Blood,"Action, Adventure",7.7,Ted Kotcheff,5
5,"Aguirre, der Zorn Gottes","Action, Adventure, Biography",7.9,Werner Herzog,1
6,Sholay,"Action, Adventure, Comedy",8.2,Ramesh Sippy,1
7,The General,"Action, Adventure, Comedy",8.1,Clyde Bruckman,2
8,Bajrangi Bhaijaan,"Action, Adventure, Comedy",8.0,Kabir Khan,3
9,Guardians of the Galaxy,"Action, Adventure, Comedy",8.0,James Gunn,3
10,Deadpool,"Action, Adventure, Comedy",8.0,Tim Miller,3
11,Thor: Ragnarok,"Action, Adventure, Comedy",7.9,Taika Waititi,6
12,The Blues Brothers,"Action, Adventure, Comedy",7.9,John Landis,6
13,Deadpool 2,"Action, Adventure, Comedy",7.7,David Leitch,8
14,Kingsman: The Secret Service,"Action, Adventure, Comedy",7.7,Matthew Vaughn,8
15,Guardians of the Galaxy Vol. 2,"Action, Adventure, Comedy",7.6,James Gunn,10
16,Celda 211,"Action, Adventure, Crime",7.6,Daniel Monzón,1
17,The Lord of the Rings: The Return of the King,"Action, Adventure, Drama",8.9,Peter Jackson,1
18,The Lord of the Rings: The Fellowship of the Ring,"Action, Adventure, Drama",8.8,Peter Jackson,2
19,The Lord of the Rings: The Two Towers,"Action, Adventure, Drama",8.7,Peter Jackson,3
20,Shichinin no samurai,"Action, Adventure, Drama",8.6,Akira Kurosawa,4
21,Gladiator,"Action, Adventure, Drama",8.5,Ridley Scott,5
22,Avengers: Endgame,"Action, Adventure, Drama",8.4,Anthony Russo,6
23,The Revenant,"Action, Adventure, Drama",8.0,Alejandro G. Iñárritu,7
24,Letters from Iwo Jima,"Action, Adventure, Drama",7.9,Clint Eastwood,8
25,Apocalypto,"Action, Adventure, Drama",7.8,Mel Gibson,9
26,The Count of Monte Cristo,"Action, Adventure, Drama",7.8,Kevin Reynolds,9
27,Red River,"Action, Adventure, Drama",7.8,Howard Hawks,9
28,The Last of the Mohicans,"Action, Adventure, Drama",7.7,Michael Mann,12
29,Dawn of the Planet of the Apes,"Action, Adventure, Drama",7.6,Matt Reeves,13

---
# ***SQL Mini Exercises***
---

---
# ***Exercise 1 — Movies where Gross > 100M***
---

In [54]:
query = """
SELECT Series_Title, IMDB_Rating, Gross
FROM movies
WHERE GROSS > 100000000
ORDER BY IMDB_Rating DESC
"""
result = pd.read_sql_query(query, conn)
print(f"Movies grossing over 100M : {len(result)}")
print(result.head(10).to_string(index=False))

Movies grossing over 100M : 187
                                     Series_Title  IMDB_Rating       Gross
                                    The Godfather          9.2 134966411.0
                                  The Dark Knight          9.0 534858444.0
    The Lord of the Rings: The Return of the King          8.9 377845905.0
                                     Pulp Fiction          8.9 107928762.0
                                        Inception          8.8 292576195.0
The Lord of the Rings: The Fellowship of the Ring          8.8 315544750.0
                                     Forrest Gump          8.8 330252182.0
            The Lord of the Rings: The Two Towers          8.7 342551365.0
                                       The Matrix          8.7 171479930.0
   Star Wars: Episode V - The Empire Strikes Back          8.7 290475067.0

---
# ***Exercise 2 — Directors with 3+ movies***
---

In [56]:
query = """
SELECT Director, COUNT(*) as movie_count
FROM movies
GROUP BY Director
HAVING movie_count >= 3
ORDER BY movie_count DESC
"""
result = pd.read_sql_query(query, conn)
print(f"Directors with 3+ movies in IMDb Top 1000 : {len(result)}")
print(result.to_string(index=False))

Directors with 3+ movies in IMDb Top 1000 : 97
             Director  movie_count
     Alfred Hitchcock           14
     Steven Spielberg           13
       Hayao Miyazaki           11
      Martin Scorsese           10
       Akira Kurosawa           10
          Woody Allen            9
      Stanley Kubrick            9
         Billy Wilder            9
    Quentin Tarantino            8
        David Fincher            8
       Clint Eastwood            8
    Christopher Nolan            8
           Rob Reiner            7
       Ingmar Bergman            7
         Howard Hawks            7
         Wes Anderson            6
         Sergio Leone            6
         Ridley Scott            6
    Richard Linklater            6
            Joel Coen            6
      Charles Chaplin            6
       Alfonso Cuarón            6
         Sidney Lumet            5
           Ron Howard            5
       Roman Polanski            5
      Robert Zemeckis            5
        Peter Jackson            5
          John Huston            5
            John Ford            5
        James Cameron            5
 Francis Ford Coppola            5
     Federico Fellini            5
     Denis Villeneuve            5
          David Lynch            5
     Andrei Tarkovsky            5
        Terry Gilliam            4
            Spike Lee            4
           Sam Mendes            4
      Rajkumar Hirani            4
          Pete Docter            4
        Neeraj Pandey            4
       Matthew Vaughn            4
 Krzysztof Kieslowski            4
        James Mangold            4
          Guy Ritchie            4
       Fred Zinnemann            4
          Frank Capra            4
           David Lean            4
       Chan-wook Park            4
            Brad Bird            4
       Asghar Farhadi            4
        Anthony Russo            4
              Ang Lee            4
Alejandro G. Iñárritu            4
        William Wyler            3
         Tom McCarthy            3
           Tim Burton            3
    Thomas Vinterberg            3
      Terrence Malick            3
        Taika Waititi            3
       Stanley Kramer            3
          Spike Jonze            3
          Satoshi Kon            3
         Ron Clements            3
      Pedro Almodóvar            3
 Paul Thomas Anderson            3
      Paul Greengrass            3
       Norman Jewison            3
         Michael Mann            3
       Michael Haneke            3
           Mel Gibson            3
          Luis Buñuel            3
       Lars von Trier            3
         Kar-Wai Wong            3
       John McTiernan            3
          John Hughes            3
         Jim Sheridan            3
         Jim Jarmusch            3
          James Whale            3
          J.J. Abrams            3
        Isao Takahata            3
   Giuseppe Tornatore            3
Franklin J. Schaffner            3
       Emir Kusturica            3
           Elia Kazan            3
         Edward Zwick            3
         Edgar Wright            3
           Don Siegel            3
          David Yates            3
     Darren Aronofsky            3
          Danny Boyle            3
         Bryan Singer            3
       Brian De Palma            3
         Bong Joon Ho            3
   Andrey Zvyagintsev            3
   Alejandro Amenábar            3
          Alan Parker            3

---
# ***Exercise 3 — Movies above average rating using subquery***
---

In [62]:
query = """
SELECT Series_Title, IMDB_Rating, Director
FROM movies
WHERE IMDB_Rating > (SELECT AVG(IMDB_Rating) FROM movies)
ORDER BY IMDB_Rating DESC
"""
result = pd.read_sql_query(query, conn)
avg_query = "SELECT ROUND(AVG(IMDB_Rating),3) as avg_rating FROM movies"
avg_rating = pd.read_sql_query(avg_query, conn).iloc[0, 0]
print(f"Overall average rating : {avg_rating}")
print(f"Movies above average   : {len(result)}")
print(f"That's {len(result)/10:.1f}%  of the top 1000\n")
print(result.head(10).to_string(index=False))

Overall average rating : 7.949
Movies above average   : 463
That's 46.3%  of the top 1000

                                 Series_Title  IMDB_Rating             Director
                     The Shawshank Redemption          9.3       Frank Darabont
                                The Godfather          9.2 Francis Ford Coppola
                              The Dark Knight          9.0    Christopher Nolan
                       The Godfather: Part II          9.0 Francis Ford Coppola
                                 12 Angry Men          9.0         Sidney Lumet
The Lord of the Rings: The Return of the King          8.9        Peter Jackson
                                 Pulp Fiction          8.9    Quentin Tarantino
                             Schindler's List          8.9     Steven Spielberg
                                    Inception          8.8    Christopher Nolan
                                   Fight Club          8.8        David Fincher